# Generated by Django 3.1.1 on 2021-01-09 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210109_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 16, 37, 49, 221499, tzinfo=utc)),
        ),
    ]
